package com.moniday.enums

enum Currency {
    NotSpecified("Not specified."),
    XXX("No currency"),
    AED("United Arab Emirates dirham"),
    AFN("Afghan afghani"),
    ALL("Albanian lek"),
    AMD("Armenian dram"),
    ANG("Netherlands Antillean guilder"),
    AOA("Angolan kwanza"),
    ARS("Argentine peso"),
    AUD("Australian dollar"),
    AWG("Aruban florin"),
    AZN("Azerbaijani manat"),
    BAM("Bosnia and Herzegovina convertible mark"),
    BBD("Barbados dollar"),
    BDT("Bangladeshi taka"),
    BGN("Bulgarian lev"),
    BHD("Bahraini dinar"),
    BIF("Burundian franc"),
    BMD("Bermudian dollar"),
    BND("Brunei dollar"),
    BOB("Boliviano"),
    BOV("Bolivian Mvdol (funds code)"),
    BRL("Brazilian real"),
    BSD("Bahamian dollar"),
    BTN("Bhutanese ngultrum"),
    BWP("Botswana pula"),
    BYR("Belarusian ruble"),
    BZD("Belize dollar"),
    CAD("Canadian dollar"),
    CDF("Congolese franc"),
    CHE("WIR Euro (complementary currency)"),
    CHF("Swiss franc"),
    CHW("WIR Franc (complementary currency)"),
    CLF("Unidad de Fomento (funds code)"),
    CLP("Chilean peso"),
    CNY("Chinese yuan"),
    COP("Colombian peso"),
    COU("Unidad de Valor Real (UVR) (funds code)[7]"),
    CRC("Costa Rican colon"),
    CUC("Cuban convertible peso"),
    CUP("Cuban peso"),
    CVE("Cape Verde escudo"),
    CZK("Czech koruna"),
    DJF("Djiboutian franc"),
    DKK("Danish krone"),
    DOP("Dominican peso"),
    DZD("Algerian dinar"),
    EGP("Egyptian pound"),
    ERN("Eritrean nakfa"),
    ETB("Ethiopian birr"),
    EUR("Euro"),
    FJD("Fiji dollar"),
    FKP("Falkland Islands pound"),
    GBP("Pound sterling"),
    GEL("Georgian lari"),
    GHS("Ghanaian cedi"),
    GIP("Gibraltar pound"),
    GMD("Gambian dalasi"),
    GNF("Guinean franc"),
    GTQ("Guatemalan quetzal"),
    GYD("Guyanese dollar"),
    HKD("Hong Kong dollar"),
    HNL("Honduran lempira"),
    HRK("Croatian kuna"),
    HTG("Haitian gourde"),
    HUF("Hungarian forint"),
    IDR("Indonesian rupiah"),
    ILS("Israeli new shekel"),
    INR("Indian rupee"),
    IQD("Iraqi dinar"),
    IRR("Iranian rial"),
    ISK("Icelandic króna"),
    JMD("Jamaican dollar"),
    JOD("Jordanian dinar"),
    JPY("Japanese yen"),
    KES("Kenyan shilling"),
    KGS("Kyrgyzstani som"),
    KHR("Cambodian riel"),
    KMF("Comoro franc"),
    KPW("North Korean won"),
    KRW("South Korean won"),
    KWD("Kuwaiti dinar"),
    KYD("Cayman Islands dollar"),
    KZT("Kazakhstani tenge"),
    LAK("Lao kip"),
    LBP("Lebanese pound"),
    LKR("Sri Lankan rupee"),
    LRD("Liberian dollar"),
    LSL("Lesotho loti"),
    LTL("Lithuanian litas"),
    LYD("Libyan dinar"),
    MAD("Moroccan dirham"),
    MDL("Moldovan leu"),
    MGA("Malagasy ariary"),
    MKD("Macedonian denar"),
    MMK("Myanmar kyat"),
    MNT("Mongolian tugrik"),
    MOP("Macanese pataca"),
    MRO("Mauritanian ouguiya"),
    MUR("Mauritian rupee"),
    MVR("Maldivian rufiyaa"),
    MWK("Malawian kwacha"),
    MXN("Mexican peso"),
    MXV("Mexican Unidad de Inversion(UDI) (funds code)"),
    MYR("Malaysian ringgit"),
    MZN("Mozambican metical"),
    NAD("Namibian dollar"),
    NGN("Nigerian naira"),
    NIO("Nicaraguan córdoba"),
    NOK("Norwegian krone"),
    NPR("Nepalese rupee"),
    NZD("New Zealand dollar"),
    OMR("Omani rial"),
    PAB("Panamanian balboa"),
    PEN("Peruvian nuevo sol"),
    PGK("Papua New Guinean kina"),
    PHP("Philippine peso"),
    PKR("Pakistani rupee"),
    PLN("Polish złoty"),
    PYG("Paraguayan guaraní"),
    QAR("Qatari riyal"),
    RON("Romanian new leu"),
    RSD("Serbian dinar"),
    RUB("Russian ruble"),
    RWF("Rwandan franc"),
    SAR("Saudi riyal"),
    SBD("Solomon Islands dollar"),
    SCR("Seychelles rupee"),
    SDG("Sudanese pound"),
    SEK("Swedish krona/kronor"),
    SGD("Singapore dollar"),
    SHP("Saint Helena pound"),
    SLL("Sierra Leonean leone"),
    SOS("Somali shilling"),
    SRD("Surinamese dollar"),
    SSP("South Sudanese pound"),
    STD("Sao Tomé and Príncipe dobra"),
    SYP("Syrian pound"),
    SZL("Swazi lilangeni"),
    THB("Thai baht"),
    TJS("Tajikistani somoni"),
    TMT("Turkmenistani manat"),
    TND("Tunisian dinar"),
    TOP("Tongan pa'anga"),
    TRY("Turkish lira"),
    TTD("Trinidad and Tobago dollar"),
    TWD("New Taiwan dollar"),
    TZS("Tanzanian shilling"),
    UAH("Ukrainian hryvnia"),
    UGX("Ugandan shilling"),
    USD("United States dollar"),
    USN("United States dollar (next day) (funds code)"),
    USS("United States dollar (same day) (funds code)[10]"),
    UYI("Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"),
    UYU("Uruguayan peso"),
    UZS("Uzbekistan som"),
    VEF("Venezuelan bolívar"),
    VND("Vietnamese dong"),
    VUV("Vanuatu vatu"),
    WST("Samoan tala"),
    XAF("CFA franc BEAC"),
    XAG("Silver (one troy ounce)"),
    XAU("Gold (one troy ounce)"),
    XBA("European Composite Unit(EURCO) (bond market unit)"),
    XBB("European Monetary Unit(E.M.U.-6) (bond market unit)"),
    XBC("European Unit of Account 9(E.U.A.-9) (bond market unit)"),
    XBD("European Unit of Account 17(E.U.A.-17) (bond market unit)"),
    XBT("bitcoinInternational internet currency"),
    XCD("East Caribbean dollar"),
    XDR("Special drawing rights"),
    XFU("UIC franc(special settlement currency)"),
    XOF("CFA franc BCEAO"),
    XPD("Palladium (onetroy ounce)"),
    XPF("CFP franc(franc Pacifique)"),
    XPT("Platinum (onetroy ounce)"),
    XSU("SUCRE"),
    XTS("Code reserved for testing purposes"),
    XUA("ADB Unit of Account"),
    YER("Yemeni rial"),
    ZAR("South African rand"),
    ZMW("Zambian kwacha"),
    ZWD("Zimbabwe dollar")

    private final String value

    Currency(String value) {
        this.value = value
    }

    public String getValue() {
        return value
    }

    public String getKey() {
        return name()
    }

    String toString() {
        return value
    }

    public static list() {
        [GBP, EUR]
    }
}